baseURL = "https://piotr-rusin.github.io"
languageCode = "en-us"
title = "Reusing the wheel"
theme = "mainroad"

[Params.widgets]
    search = true
    recent_articles = true
    recent_articles_num = 5
    categories = true
    tags = true
