baseURL = "https://piotr-rusin.github.io"
languageCode = "en-us"
title = "Reusing the wheel"
theme = "rtw-2020"
disqusShortname = "piotr-rusin-github-io"
googleAnalytics = "UA-109495807-1"

pygmentsCodefences = true
pygmentsStyle = "borland"

[permalinks]
  posts = "/posts/:year-:month-:day-:filename/"

[menu]
  # Header
  [[menu.left]]
    url = "/tags/java"
    name = "Java"
    weight = 2
  [[menu.left]]
    url = "/tags/python"
    name = "Python"
    weight = 3
  [[menu.left]]
    url = "/tags/spring"
    name = "Spring"
    weight = 4
  [[menu.left]]
    url = "/tags/"
    name = "More..."
    weight = 5
  [[menu.right]]
    url = "/about/"
    name = "about"
  [[menu.right]]
    url = "mailto:piotr.rusin88@gmail.com"
    name = "Contact"
  [[menu.right]]
    url = "https://github.com/piotr-rusin"
    name = "Github"

[Params]
    readmore = true
    homeLinkText = "RTW"

[Params.widgets]
    recent_articles = true
    recent_articles_num = 5
    categories = true
    tags = true
    social_github = "piotr-rusin"
    social_email = "piotr.rusin88@gmail.com"

[taxonomies]
    tag = "tags"
    category = "categories"
    project = "projects"
