baseURL = "https://piotr-rusin.github.io"
languageCode = "en-us"
title = "Reusing the wheel"
theme = "mainroad"
disqusShortname = "piotr-rusin.github.io"
googleAnalytics = "UA-109495807-1"

[[menu.main]]
    name = "Posts"
    weight = -100
    url = "/"

[Params]
    readmore = true

[Params.widgets]
    search = true
    recent_articles = true
    recent_articles_num = 5
    categories = true
    tags = true
    social_github = "piotr-rusin"
    social_email = "piotr.rusin88@gmail.com"
