baseURL = "https://piotr-rusin.github.io"
languageCode = "en-us"
title = "Reusing the wheel"
theme = "rtw"
disqusShortname = "piotr-rusin-github-io"
googleAnalytics = "UA-109495807-1"

pygmentsCodefences = true
pygmentsStyle = "borland"

[permalinks]
  post = "/:year/:month/:title/"

[[menu.main]]
    name = "Posts"
    weight = -100
    url = "/"

[Params]
    readmore = true

[Params.widgets]
    recent_articles = true
    recent_articles_num = 5
    categories = true
    tags = true
    social_github = "piotr-rusin"
    social_email = "piotr.rusin88@gmail.com"

[taxonomies]
    tag = "tags"
    category = "categories"
    project = "projects"
