baseURL = "https://piotr-rusin.github.io/"
languageCode = "en-us"
title = "Reusing the wheel"
theme = "hyde"
# disqusShortname = "piotr-rusin-github-io"
googleAnalytics = "UA-109495807-1"

pygmentsCodefences = true
pygmentsStyle = "borland"

[permalinks]
  posts = "/posts/:year-:month-:day-:filename/"

[menu]
  [[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 5
  [[menu.main]]
    url = "/about/"
    name = "About"

[Params]
  description = "A blog about programming"
    readmore = true
    homeLinkText = "Reusing the wheel"

[Params.widgets]
    recent_articles = true
    recent_articles_num = 5
    categories = true
    tags = true
    social_github = "piotr-rusin"
    social_email = "piotr.rusin88@gmail.com"

[taxonomies]
    category = "categories"
    project = "projects"
